[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[lib]
name = "aoc"
path = "src/lib.rs"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
fancy-regex = "0.17.0"
indicatif = "0.18.3"
rangemap = "1.7.1"
